Add polyfill links
tc39/proposal-collection-methods pull request #29
Opened 2019-01-15 22:59 UTC by metreniuk

I have added the polyfill section with links to `core-js` library. I also added some examples on how to use it.

2019-01-15 23:45 UTC, ljharb requested changes

2019-01-15 23:45 UTC, ljharb commented on README.md
> +The polyfill is available in the [core-js](https://github.com/zloirock/core-js) library.
```suggestion
A polyfill is available in the [core-js](https://github.com/zloirock/core-js) library.
```

2019-01-16 12:57 UTC, Ginden commented
LGTM

2019-03-20 23:35 UTC, zloirock commented
So...?

More other, now it's available in `babel` `preset-env` and `runtime` with `corejs: { version: 3, proposals: true }` option.

2019-03-21 13:34 UTC, merged